version: 2
jobs:
  build:
    working_directory: ~/branch-manager
    docker:
      - image: circleci/node:7.10.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - branch-manager-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build
          command: yarn dist
      - run:
          name: Lint
          command: yarn lint
      - save_cache:
          key: branch-manager-{{ checksum "yarn.lock" }}
          paths:
            - ~/.yarn-cache
      - deploy:
          name: Publish to NPM if tagged
          working_directory: ~/branch-manager/build
          command: |
            set -euo pipefail
            TAG=${CIRCLE_TAG:-}
            if [[ ${TAG} =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
              npm publish
            else
              echo "Not publishing: build was not triggered by a proper release tag"
            fi

deployment:
  npm:
    tag: /^[0-9]+\.[0-9]+\.[0-9]+$/
